<div class="span12" ng-controller="usuario_mensagem_usersCTRL">
    <button class="span4 btn" ng-click="setUsers()" ng-class="{'btn-primary':(last === 'users')}">Usuários</button>
    <button class="span4 btn" ng-click="setGroups()" ng-class="{'btn-primary':(last === 'groups')}">Grupos</button>
    <div class="list-group span12">
        <input type="text" placeholder="Buscar Usuários" class="span12" ng-show="(last === 'users')" ng-hide="hideForm" ng-model="search"/>
        <div id='userlist_container'>
            <div class="container span12" ng-show='active.length'>
                <div class="list-group-item span11"
                     ng-repeat="group in active" 
                     ng-class="{'label-warning':group.unread}"
                     ng-click="current(group)"
                >
                    <a>
                        <span class="list-group-item-heading">{{getName(group)}}</span>
                        <span class="badge" ng-hide="!group.unread">{{group.unread}}</span>
                    </a>
                </div>
            </div>
        </div>
        <button ng-click="loadMore()" ng-hide="hideButton()" class="span11">Mais Usuários</button>
    </div>
</div>