<div class="" ng-controller="usuario_mensagemCTRL">
    <div class="bs-callout"
        ng-repeat="msg in messages" 
        ng-class="{
             'bs-callout-danger'       :(msg.visualizada == 's'),
             'bs-callout-warning'      :(msg.from == user.cod_usuario),
             'bs-callout-info margin15':(msg.from == sender.cod_usuario),
        }">
        <div class=""><a href="{{url}}/{{msg.from}}" target="_BLANK">{{msg.fromname}}</a> - {{msg.data|fromNow}}</div>
        <div class="msgbox" ng-bind-html="msg.mensagem"></div>
    </div>
    <button ng-click="getMessages()" ng-hide="hideButton()" class="col-lg-12">Mais mensagens</button>
    <div ng-show="stop" class="col-lg-12 margin15 bs-callout bs-callout-danger">Não existem mais mensagens nesta conversa!</div>
</div>