<div ng-controller="usuario_mensagem_usersCTRL" ng-hide="hideall">
    <div style='border:1px solid transparent;'>
        <button 
            class="col-lg-6 col-md-6 col-sm-12 btn btn-lg" 
            ng-click="setUsers(lastUser)"   
            ng-class="{'btn-primary':(useractive)}"
        >
            <i class="fa fa-user"></i> Usuários
        </button>
        <button 
            class="col-lg-6 col-md-6 col-sm-12 btn btn-lg" 
            ng-click="setGroups(lastGroup)" 
            ng-class="{'btn-primary':(!useractive)}"
        >
            <i class="fa fa-users"></i>Grupos
        </button>
    </div>
    <div class="clearfix"></div>
    <div style="margin: 8px 0 8px 0;">
        <input type="text" 
               placeholder="Buscar Usuários" 
               class="form-control" 
               ng-show="(useractive && !hideForm)"
               ng-model="search"
               ng-model-options="{ debounce: 300 }"
               style="margin-top: 5px;"
        />
        <ul ng-show='active.length' >
            <li class="list-group-item"
                 ng-repeat="group in active" 
                 ng-class="{
                     'label-warning':group.unread,
                     'active'       :(isActive(group)) 
                 }"
                 ng-click="setCurrent(group)"
                 style="cursor: pointer;"
            >
                <a>
                    <span class="list-group-item-heading">{{getData('name',group)}}</span>
                    <span class="badge" ng-hide="!group.unread">{{group.unread}}</span>
                </a>
            </li>
        </ul>
        <div ng-hide="!useractive || last == 1">
            <div ng-hide="search.length > 0">Página atual: {{page}} de {{last}}</div>
            <button ng-click="loadPage(1)"      ng-class="{'disabled':(search.length > 0 ||page===1    ||busy)}"                 class="btn btn-success col-lg-3">First</button>
            <button ng-click="loadPage(page-1)" ng-class="{'disabled':(search.length > 0 ||page===1    ||busy)}"                 class="btn btn-success col-lg-3"><i class="fa fa-arrow-circle-left"></i></button>
            <button ng-click="loadPage(page+1)" ng-class="{'disabled':(search.length > 0 ||page=== last||busy)}"                 class="btn btn-success col-lg-3"><i class="fa fa-arrow-circle-right"></i></button>
            <button ng-click="loadPage(last)"   ng-class="{'disabled':(search.length > 0 ||last == 0   ||busy|| page=== last )}" class="btn btn-success col-lg-3">Last</button>
        </div>
    </div>
</div>