<div ng-controller="message_user_formCTRL" class="col-xs-12">
    <div ng-show="cansend">
        <textarea placeholder="Escreva uma mensagem" 
                  ng-model="content" 
                  redactor="redactorOptions"></textarea>
        <button class="btn btn-success btn-lg col-xs-12 col-sm-6 col-md-4 col-lg-2" ng-click="sendMessage()" style="margin-top: 5px;">Enviar</button>
    </div>
    <h4 ng-hide="cansend">
        Você não pode enviar mensagens nesta conversa
    </h4>
</div>