<div id='msgs_ctrl' ng-controller="message_userCTRL">
    <div 
        class="bs-callout" 
        ng-repeat="msg in messages" 
        ng-class="{
            'bs-callout-danger':(msg.visualizada === 's'),
            'active':(msg.visualizada === 'n' && msg.from === user.cod_usuario)
        }">
        <div class=""><a href="{{url}}/{{msg.from}}" target="_BLANK">{{msg.fromname}}</a> - {{msg.data|fromNow}}</div>
        <div class="" ng-bind-html="msg.mensagem"></div>
    </div>
    <button ng-click="getMessages()" ng-hide="hideButton()" class="col-lg-12">Mais mensagens</button>
    <div ng-show="stop" class="col-lg-12 box-content">Não existem mais mensagens nesta conversa!</div>
</div>