<?php 
    $this->Html->LoadBowerComponent(array(
        'moment/min/moment.min','moment/locale/pt-br', 'tinymce/tinymce.min',
        'angular/angular.min', 'angular-sanitize/angular-sanitize.min', 
        'redactor/redactor/redactor.min', 
        'hatframework-hatjs-form/redactor/fullscreen',
        'hatframework-hatjs-form/redactor/redactor.directive.min',
    ));
    $this->Html->LoadBowerComponentCss(array(
        'redactor/redactor/redactor', 
    ));

    $location = "/app/js";
    $this->Html->LoadJs(array("lib/baseurl", 'lib/haturl'));
    $this->Html->LoadPlugin('mensagem',array(
        "$location/app.js", "$location/sync.js",
        "$location/formulario.js", "$location/messages.js",
        "$location/users.js", "$location/talkWith.js",
    ));

    $dir = classes\Classes\Registered::getPluginLocation('mensagem', true).DS."app".DS."html";
?>
<div ng-app="usuario_messageApp">
    <div class="col-lg-9 col-md-8 pull-right">
        <?php
            require_once $dir.'/talkWith.phtml';
            require_once $dir.'/formulario.phtml';
            require_once $dir.'/messages.phtml';
        ?>
    </div>
    <div class="col-lg-3 col-md-4" id='users_container'>
        <?php
            require_once $dir.'/users.phtml';
        ?>
        <div ng-controller="usuario_mensagem_syncCTRL"></div>
    </div>
    
    <style>
        #users_container ul{
            padding-left: 0;
        }
    </style>
</div>