<div class="span12" ng-app="usuario_messageApp">
    <?php 
        
        $this->Html->LoadBowerComponent(array(
            'moment/min/moment.min','moment/locale/pt-br', 'tinymce/tinymce.min',
            'angular/angular.min', 'angular-sanitize/angular-sanitize.min', 
            //'imperavi-redactor-widget/assets/redactor.min', 
            'redactor/redactor/redactor.min', 
            'hatframework-hatjs-form/redactor/fullscreen',
            'hatframework-hatjs-form/redactor/redactor.directive.min',
            //'hatframework-hatjs-form/redactor/redactor',
            //'angular-redactor/angular-redactor'
        ));
        $this->Html->LoadBowerComponentCss(array(
            //'hatframework-hatjs-form/redactor/redactor.min',
            'redactor/redactor/redactor', 
            //'imperavi-redactor-widget/assets/redactor'
        ));
        
        $location = \classes\Classes\Registered::getPluginLocationUrl('mensagem')."/mensagem/js";
        $this->Html->LoadJs(array(
            "$location/app.js", "$location/sync.js",
            "$location/formulario.js", "$location/messages.js",
            "$location/users.js", "$location/talkWith.js",
            "lib/baseurl", 'lib/haturl'
        ), true);

    ?>
    <div class="span9 pull-right">
        <?php
            require_once __DIR__.'/app/talkWith.phtml';
            require_once __DIR__.'/app/formulario.phtml';
            require_once __DIR__.'/app/messages.phtml';
        ?>
    </div>
    <div class="span3 hidden-phone" id='users_container'>
        <?php
            require_once __DIR__.'/app/users.phtml';
        ?>
        
        <div ng-controller="usuario_mensagem_syncCTRL"></div>
    </div>
    
    <style>
        .unread{
            border-left: 8px solid #f50000!important;
        }
        .read{
            border-left: 8px solid gray!important;
        }
        .sub-footer, .footer, .breadcrumb{
            display: none;
        }
        #conteudo {margin-bottom: 0px; padding-bottom: 0px;}
        #users_container{}
        #userlist_container{overflow-y:scroll; overflow-x: hidden;}
        .user_box{
            margin-top: 5px; cursor: pointer;
        }
        .user_box:hover{
           opacity: 0.6;
        }
        .msg_container{margin-top: 5px;}
    </style>
</div>