<?php

$url  = classes\Classes\Registered::getPluginLocationUrl('mensagem')."/Config/img/";
$url2 = $this->Html->getLink("mensagem/mensagem/moderador");
$url3 = $this->Html->getLink("mensagem/mensagem/usuario");

?>
<div class="col-sm-6 col-md-4 col-md-offset-2">
    <div class="thumbnail">
         <a href="<?php echo $url2; ?>">
             <img class="col-xs-12" height="100px" src="<?php echo "$url/moderador1.png";?>">
         </a>
      <div class="caption">
        <h3>Acesse o sistema como moderador</h3>
        <p>
            <a class="btn btn-lg btn-primary btn-block" role="Entrar" href="<?php echo $url2; ?>">Entrar como Moderador</a>
        </p>
      </div>
    </div>
</div>
<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
         <a href="<?php echo $url3; ?>">
             <img class="col-xs-12" height="100px" src="<?php echo "$url/user_big.png";?>">
         </a>
      <div class="caption">
        <h3>Acesse o sistema como usuário</h3>
        <p>
            <a class="btn btn-lg btn-primary btn-block" role="Entrar" href="<?php echo $url3; ?>">Entrar como Usuário</a>
        </p>
      </div>
    </div>
</div>
