<?php 
    $this->Html->LoadBowerComponent(array(
        'moment/min/moment.min','moment/locale/pt-br', 'tinymce/tinymce.min',
        'angular/angular.min', 'angular-sanitize/angular-sanitize.min', 
        'redactor/redactor/redactor.min', 
        'hatframework-hatjs-form/redactor/fullscreen',
        'hatframework-hatjs-form/redactor/redactor.directive.min',
    ), array(
        'redactor/redactor/redactor', 
    ));
    //$url = \classes\Classes\Registered::getResourceLocationUrl('upload')."/src/jsplugins/redactor/plugins/imagemanager";

    $location = "/app/moderador/js/";
    $this->Html->LoadJs(array("lib/baseurl", 'lib/haturl'));
    $this->Html->LoadPlugin('mensagem',array(
        "$location/app.js", "$location/sync.js",
        "$location/formulario.js", "$location/messages.js",
        "$location/users.js", "$location/talkWith.js",
    ));

    $dir = classes\Classes\Registered::getPluginLocation('mensagem', true).DS."app".DS.'moderador'.DS."html";
?>
<div ng-app="usuario_messageApp">
    <div ng-controller="usuario_mensagem_globalCTRL" ng-class="{'col-lg-9 col-md-8 col-sm-8 col-xs-12 pull-right':hideall}">
        <?php
            require_once $dir.'/talkWith.phtml';
            require_once $dir.'/formulario.phtml';
            require_once $dir.'/messages.phtml';
        ?>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12" id='users_container'>
        <?php
            require_once $dir.'/users.phtml';
        ?>
        <div ng-controller="usuario_mensagem_syncCTRL"></div>
    </div>
    
    <style type="text/css">
        #users_container ul{
            padding-left: 0;
        }
        .margin15{
            margin-left: 35px;
        }
        .msgbox img{
            width: 98%; // Force IE10 and below to size SVG images correctly
            max-width: 600px; // Part 1: Set a maximum relative to the parent
            margin: 3px;
        }
    </style>
</div>